package com.example.administrator.daiylywriting.BooksSqilte;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SETTING.
 */
public class Setting {

    private Long id;
    private Integer TimeToSearch;
    private Boolean isWebSearch;
    private String WebAddress;
    private Boolean isItemAdd;

    public Setting() {
    }

    public Setting(Long id) {
        this.id = id;
    }

    public Setting(Long id, Integer TimeToSearch, Boolean isWebSearch, String WebAddress, Boolean isItemAdd) {
        this.id = id;
        this.TimeToSearch = TimeToSearch;
        this.isWebSearch = isWebSearch;
        this.WebAddress = WebAddress;
        this.isItemAdd = isItemAdd;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getTimeToSearch() {
        return TimeToSearch;
    }

    public void setTimeToSearch(Integer TimeToSearch) {
        this.TimeToSearch = TimeToSearch;
    }

    public Boolean getIsWebSearch() {
        return isWebSearch;
    }

    public void setIsWebSearch(Boolean isWebSearch) {
        this.isWebSearch = isWebSearch;
    }

    public String getWebAddress() {
        return WebAddress;
    }

    public void setWebAddress(String WebAddress) {
        this.WebAddress = WebAddress;
    }

    public Boolean getIsItemAdd() {
        return isItemAdd;
    }

    public void setIsItemAdd(Boolean isItemAdd) {
        this.isItemAdd = isItemAdd;
    }

}
